/**
 * OkeyScout — Supabase Client & Types
 * src/services/supabase.ts
 *
 * Initialize the Supabase client.
 * Replace VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY with your project credentials.
 * See: https://app.supabase.com → Your Project → Settings → API
 */

// ─────────────────────────────────────────────────────────────────────────────
// Database Types (mirror the schema in supabase_schema.sql)
// These types are auto-generated by the Supabase CLI: npx supabase gen types typescript
// ─────────────────────────────────────────────────────────────────────────────

export type Json = Record<string, unknown>;

export interface Profiles {
  id:         string;          // uuid
  username:   string;
  avatar_url: string | null;
  created_at: string;          // timestamptz
}

export interface Tables {
  id:             string;      // text (4-digit code, e.g. '4821')
  status:         'lobby' | 'playing' | 'finished';
  current_round:  number;
  gösterge_tile:  GöstergeTile | null; // jsonb
  created_by:     string | null; // uuid
  created_at:     string;      // timestamptz
}

export interface GöstergeTile {
  color:  string;  // 'RED' | 'YELLOW' | 'BLUE' | 'BLACK'
  number: number;  // 1–13
}

export interface TablePlayers {
  id:         string;   // uuid
  table_id:   string;  // text FK → tables.id
  player_id:  string;  // uuid FK → profiles.id
  seat_index: number;  // 0–3
  is_ready:   boolean;
  is_creator: boolean;
  joined_at:  string;  // timestamptz
}

export interface Rounds {
  id:                   string;  // uuid
  table_id:             string;  // text FK → tables.id
  round_number:         number;
  gösterge_tile:        GöstergeTile;
  gösterge_player_id:   string | null; // uuid
  gösterge_confirmed_by:string | null;  // uuid
  gösterge_confirmed:  boolean;
  status:              'gösterge_selection' | 'playing' | 'finished';
  winner_id:           string | null;    // uuid
  started_at:          string | null;    // timestamptz
  finished_at:         string | null;    // timestamptz
  created_at:          string;            // timestamptz
}

// ─────────────────────────────────────────────────────────────────────────────
// Supabase Client
// ─────────────────────────────────────────────────────────────────────────────

let _client: ReturnType<typeof import('@supabase/supabase-js').createClient> | null = null;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function getSupabase(): any {
  if (!_client) {
    // Dynamic import so this file can be imported without .env during development
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { createClient } = require('@supabase/supabase-js');
    _client = createClient(
      process.env.EXPO_PUBLIC_SUPABASE_URL ?? 'https://placeholder.supabase.co',
      process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY ?? 'placeholder-anon-key',
      {
        auth: { persistSession: true, autoRefreshToken: true },
        realtime: { params: { eventsPerSecond: 10 } },
      },
    );
  }
  return _client;
}

// Convenient shorthand used throughout the app
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const supabase: any = {
  get client() { return getSupabase(); },
};

// ─────────────────────────────────────────────────────────────────────────────
// Realtime subscriptions
// ─────────────────────────────────────────────────────────────────────────────

export type PlayerJoinEvent = {
  eventType: 'INSERT' | 'DELETE' | 'UPDATE';
  new:       TablePlayers;
};

/**
 * Subscribe to player changes at a table.
 * Calls `onChange` whenever a player joins, leaves, or updates their ready status.
 */
export function subscribeToTablePlayers(
  tableId: string,
  onChange: (event: PlayerJoinEvent) => void,
) {
  const client = getSupabase();

  const channel = client
    .channel(`table_players:${tableId}`)
    .on(
      'postgres_changes',
      {
        event: '*',
        schema: 'public',
        table:  'table_players',
        filter: `table_id=eq.${tableId}`,
      },
      (payload: unknown) => {
        const p = payload as { eventType: string; new: TablePlayers };
        onChange({
          eventType: p.eventType as 'INSERT' | 'UPDATE' | 'DELETE',
          new:       p.new as TablePlayers,
        });
      },
    )
    .subscribe();

  return () => client.removeChannel(channel);
}

/**
 * Subscribe to table status changes (lobby → playing → finished).
 */
export function subscribeToTableStatus(
  tableId: string,
  onChange: (status: Tables['status']) => void,
) {
  const client = getSupabase();

  const channel = client
    .channel(`tables:${tableId}`)
    .on(
      'postgres_changes',
      {
        event: 'UPDATE',
        schema: 'public',
        table:  'tables',
        filter: `id=eq.${tableId}`,
      },
      (payload: unknown) => {
        const p = payload as { new: Tables };
        const updated = p.new as Tables;
        onChange(updated.status);
      },
    )
    .subscribe();

  return () => client.removeChannel(channel);
}

/**
 * Subscribe to gösterge confirmation for the current round.
 */
export function subscribeToGöstergeConfirmation(
  tableId: string,
  onConfirmed: (gösterge: GöstergeTile, confirmedBy: string) => void,
) {
  const client = getSupabase();

  const channel = client
    .channel(`rounds:${tableId}`)
    .on(
      'postgres_changes',
      {
        event: 'UPDATE',
        schema: 'public',
        table:  'rounds',
        filter: `table_id=eq.${tableId}`,
      },
      (payload: unknown) => {
        const p = payload as { new: Rounds };
        const round = p.new as Rounds;
        if (round.gösterge_confirmed) {
          onConfirmed(round.gösterge_tile, round.gösterge_confirmed_by ?? '');
        }
      },
    )
    .subscribe();

  return () => client.removeChannel(channel);
}

// ─────────────────────────────────────────────────────────────────────────────
// Auth helpers
// ─────────────────────────────────────────────────────────────────────────────

export async function signInAnonymously(): Promise<string | null> {
  const client = getSupabase();
  const { data, error } = await client.auth.signInAnonymously();
  if (error || !data.user) {
    console.error('[Supabase] signInAnonymously failed:', error?.message);
    return null;
  }
  return data.user.id;
}

export async function getCurrentUserId(): Promise<string | null> {
  const client = getSupabase();
  const { data } = await client.auth.getSession();
  return data.session?.user?.id ?? null;
}

export async function signOut(): Promise<void> {
  const client = getSupabase();
  await client.auth.signOut();
}
